"""add app_config

Revision ID: ca9b87f188a2
Revises: 528b80f02959
Create Date: 2026-06-15 22:33:25.685758

"""
from alembic import op
import sqlalchemy as sa


revision = 'ca9b87f188a2'
down_revision = '528b80f02959'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linkedin_client_id', sa.Text(), nullable=True),
    sa.Column('linkedin_client_secret_enc', sa.Text(), nullable=True),
    sa.Column('linkedin_redirect_uri', sa.Text(), nullable=False),
    sa.Column('setup_complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_config')
    # ### end Alembic commands ###
